# Server configuration
server:
  port: 8080 #set your port

cors:
  originPatterns: http://localhost:3000,http://localhost:8080

security:
  jwt:
    token:
      secret-key: 53ccr37
      expire-length: 3600000

# Spring Boot configuration
spring:
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345678
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    properties:
      hibernate.format_sql: true
    database: postgresql
    open-in-view: false
    generate-ddl: true

#springdoc:
#  pathsToMatch: /api/**
#  swagger-ui:
#    user-root-path: true



